Infer bigint data type
RobinBuschmann/sequelize-typescript pull request #893
Opened 2021-01-28 17:39 UTC by Brobin

This PR infers the data type of `bigint` to `DataTypes.BIGINT`. Previously, the following code produces this error when running:

` Specified type of property 'id' cannot be automatically resolved to a sequelize data type. Please define the data type manually`

```typescript
class Test extends Model {
  @PrimaryKey
  @AutoIncrement
  @Column
  id: bigint;
}
```

2021-01-28 18:41 UTC, Brobin commented
Hmm, looks like node 14 is getting a segfault after tests. Can anyone help out? I'm not quite sure why, the tests are all passing

2021-02-06 10:58 UTC, lukashroch requested changes
@Brobin, awesome, can you please update the Type inference table in readme file?

2021-02-11 21:38 UTC, lukashroch approved these changes

2021-02-14 09:12 UTC, Divlo approved these changes

2021-02-14 09:13 UTC, merged

2022-06-25 04:37 UTC, YSHIDM commented
I need Json, what can I do